pipeline:
  name: breakingchangeparentqa
  identifier: breakingchangeparentqa
  projectIdentifier: MeenaSyncStep
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: breakingchangechildqa
          project: MeenaSyncStep
          inputs:
            identifier: breakingchangechildqa
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: tes
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
          outputs:
            - name: safsaf
              value: "123"
    - stage:
        name: fsdfds
        identifier: fsdfds
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          service:
            serviceRef: kustomizeapp
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update Release Repo
                  identifier: updateReleaseRepo
                  timeout: 10m
                  spec: {}
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                  timeout: 10m
              - step:
                  type: GitOpsFetchLinkedApps
                  name: Fetch Linked Apps
                  identifier: fetchLinkedApps
                  timeout: 10m
                  spec: {}
            rollbackSteps: []
          environment:
            environmentRef: test
            deployToAll: false
            gitOpsClusters:
              - identifier: testCluster
                agentIdentifier: account.mirkobugbashbyo
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
