pipeline:
  name: childmar4local
  identifier: childmar4local
  tags: {}
  template:
    templateRef: pipelinemar4local
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: qq
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: serviceyaml
  projectIdentifier: meenalocal
  orgIdentifier: default
