pipeline:
  name: childmar4local
  identifier: childmar4local
  tags: {}
  template:
    templateRef: pipelinemar4local
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: qq
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: myservicek8s
                    serviceInputs:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          artifacts:
                            primary:
                              primaryArtifactRef: artifact
                              sources: ""
                          variables:
                            - name: releaseTag
                              type: String
                              value: "9"
  projectIdentifier: meenalocal
  orgIdentifier: default
