pipeline:
  name: childmar4in
  identifier: childmar4in
  tags: {}
  template:
    templateRef: pipelinemar4in
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: asd
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
  projectIdentifier: testrohitgitops
  orgIdentifier: default
