pipeline:
  name: childmar4in
  identifier: childmar4in
  tags: {}
  template:
    templateRef: pipelinemar4in
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: asd
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: nginx
                    serviceInputs:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          artifacts:
                            primary:
                              sources:
                                - identifier: nginx
                                  type: Gcr
                                  spec:
                                    tag: "1.0"
                          variables:
                            - name: testVar
                              type: String
                              value: ""
                            - name: test123
                              type: String
                              value: ""
                            - name: testset
                              type: String
                              value: ""
                            - name: datetime
                              type: String
                              value: ""
  projectIdentifier: testrohitgitops
  orgIdentifier: default
