pipeline:
  name: childplain
  identifier: childplain
  projectIdentifier: meenalocal
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dd
        identifier: dd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 2
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
