pipeline:
  name: dschild
  identifier: dschild
  tags: {}
  template:
    templateRef: dspipeline
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: ss
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
  projectIdentifier: meena
  orgIdentifier: default
