pipeline:
  name: parentt
  identifier: parentt
  projectIdentifier: Zendesk
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: g
        identifier: g
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childd
          project: Zendesk
          inputs:
            identifier: childd
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: d
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
          outputs:
            - name: abc
              value: "23"
