pipeline:
  name: parentmar7remote
  identifier: parentmar7remote
  projectIdentifier: meenalocal
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: kk
        identifier: kk
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childmar7inline
          project: meenalocal
          inputs:
            identifier: childmar7inline
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: ff
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
          outputs:
            - name: outpt
              value: "56"
