pipeline:
  name: parentmar4in
  identifier: parentmar4in
  projectIdentifier: testrohitgitops
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: xcv
        identifier: xcv
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childmar4in
          project: testrohitgitops
          inputs:
            identifier: childmar4in
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: asd
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
          outputs:
            - name: cvb
              value: "12"
