pipeline:
  name: parennt
  identifier: parennt
  projectIdentifier: testrohitgitops
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: chilld
          project: testrohitgitops
          inputs:
            identifier: chilld
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: as
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
          outputs:
            - name: zen
              value: "56"
