pipeline:
  name: parentmar4in
  identifier: parentmar4in
  projectIdentifier: testrohitgitops
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: xcv
        identifier: xcv
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childmar4in
          project: testrohitgitops
          inputs:
            identifier: childmar4in
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: asd
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              serviceOverrideInputs: <+input>
                              infrastructureDefinitions: <+input>
                            service:
                              serviceRef: test
                              serviceInputs:
                                serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                    variables:
                                      - name: hellop
                                        type: String
                                        value: "3"
          outputs:
            - name: cvb
              value: "125"
