apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: meena-helm-test-appset
spec:
  generators:
  - git:
      repoURL: https://github.com/wings-software/meenasync.git
      revision: custom-artifact
      files:
      - path: "helm2/app1/*/*/config.json"
  template:
    metadata:
      name: 'meena-h-app-{{cluster.name}}'
      labels:
        harness.io/envRef: '{{envTag}}'
        harness.io/serviceRef: '{{serviceTag}}'
        harness.io/buildRef: '{{releaseTag}}'
    spec:
      project: 563e7883
      source:
        repoURL: https://github.com/wings-software/meenasync.git
        targetRevision: custom-artifact
        path: "helm-nginx"
        helm:
          parameters:
            - name: replicas
              value: '{{replicas}}'
            - name: tag
              value: '{{releaseTag}}'
      destination:
        server: '{{cluster.address}}'
        namespace: citi-demo
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
